SUPPORTED_MATRIX = [
  ("windows", "amd64"),
  ("windows", "386"),
  ("darwin", "amd64"),
  ("linux", "amd64"),
  ("linux", "386"),
  ("linux", "arm64"),
  ("linux", "arm"),
  ("linux", "mips64"),
  ("linux", "mips"),
  ("linux", "mips64le"),
  ("linux", "mipsle"),
  ("linux", "ppc64"),
  ("linux", "ppc64le"),
  ("linux", "s390x"),
  ("freebsd", "amd64"),
  ("freebsd", "386"),
  ("openbsd", "amd64"),
  ("openbsd", "386"),
  ("dragonfly", "amd64"),
]
