// Code generated by protoc-gen-go.
// source: v2ray.com/core/proxy/blackhole/config.proto
// DO NOT EDIT!

/*
Package blackhole is a generated protocol buffer package.

It is generated from these files:
	v2ray.com/core/proxy/blackhole/config.proto

It has these top-level messages:
	NoneResponse
	HTTPResponse
	Response
	Config
*/
package blackhole

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Type int32

const (
	Response_None Response_Type = 0
	Response_HTTP Response_Type = 1
)

var Response_Type_name = map[int32]string{
	0: "None",
	1: "HTTP",
}
var Response_Type_value = map[string]int32{
	"None": 0,
	"HTTP": 1,
}

func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}
func (Response_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type NoneResponse struct {
}

func (m *NoneResponse) Reset()                    { *m = NoneResponse{} }
func (m *NoneResponse) String() string            { return proto.CompactTextString(m) }
func (*NoneResponse) ProtoMessage()               {}
func (*NoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HTTPResponse struct {
}

func (m *HTTPResponse) Reset()                    { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string            { return proto.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()               {}
func (*HTTPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Response struct {
	Type     Response_Type        `protobuf:"varint,1,opt,name=type,enum=v2ray.core.proxy.blackhole.Response_Type" json:"type,omitempty"`
	Settings *google_protobuf.Any `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetSettings() *google_protobuf.Any {
	if m != nil {
		return m.Settings
	}
	return nil
}

type Config struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Config) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*NoneResponse)(nil), "v2ray.core.proxy.blackhole.NoneResponse")
	proto.RegisterType((*HTTPResponse)(nil), "v2ray.core.proxy.blackhole.HTTPResponse")
	proto.RegisterType((*Response)(nil), "v2ray.core.proxy.blackhole.Response")
	proto.RegisterType((*Config)(nil), "v2ray.core.proxy.blackhole.Config")
	proto.RegisterEnum("v2ray.core.proxy.blackhole.Response_Type", Response_Type_name, Response_Type_value)
}

func init() { proto.RegisterFile("v2ray.com/core/proxy/blackhole/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xad, 0x8c, 0x51, 0xbf, 0xca, 0x18, 0xc5, 0xc3, 0xec, 0x41, 0x46, 0xf1, 0x30, 0x11,
	0xbe, 0x48, 0xbd, 0x78, 0x11, 0x74, 0x5e, 0xc4, 0x83, 0x8c, 0xd2, 0x93, 0xb7, 0x36, 0x64, 0x75,
	0xd8, 0xe5, 0x0b, 0x69, 0x14, 0xf3, 0x4b, 0xfc, 0xbb, 0x92, 0xd4, 0xe6, 0xa6, 0x78, 0xcb, 0x1b,
	0xde, 0x27, 0xef, 0x43, 0xe0, 0xf2, 0xa3, 0xd0, 0xb5, 0x45, 0x4e, 0x7b, 0xc6, 0x49, 0x0b, 0xa6,
	0x34, 0x7d, 0x5a, 0xd6, 0x74, 0x35, 0x7f, 0x7b, 0xa5, 0x4e, 0x30, 0x4e, 0x72, 0xbb, 0x6b, 0x51,
	0x69, 0x32, 0x94, 0x66, 0x63, 0x59, 0x0b, 0xf4, 0x45, 0x0c, 0xc5, 0xec, 0xb4, 0x25, 0x6a, 0x3b,
	0xff, 0x80, 0xa1, 0xe6, 0x7d, 0xcb, 0x6a, 0x69, 0x07, 0x2c, 0x9f, 0xc1, 0xf1, 0x33, 0x49, 0x51,
	0x8a, 0x5e, 0x91, 0xec, 0x85, 0xcb, 0x8f, 0x55, 0xb5, 0x09, 0xf9, 0x2b, 0x82, 0x78, 0x0c, 0xe9,
	0x2d, 0x4c, 0x8c, 0x55, 0x62, 0x11, 0x2d, 0xa3, 0xd5, 0xac, 0xb8, 0xc0, 0xdf, 0x27, 0x71, 0x64,
	0xb0, 0xb2, 0x4a, 0x94, 0x1e, 0x4b, 0xaf, 0x20, 0xee, 0x85, 0x31, 0x3b, 0xd9, 0xf6, 0x8b, 0xc3,
	0x65, 0xb4, 0x4a, 0x8a, 0x13, 0x1c, 0xcc, 0x70, 0x34, 0xc3, 0x7b, 0x69, 0xcb, 0xd0, 0xca, 0x33,
	0x98, 0x38, 0x3e, 0x8d, 0x61, 0xe2, 0x2c, 0xe7, 0x07, 0xee, 0xe4, 0xfc, 0xe6, 0x51, 0xfe, 0x04,
	0xd3, 0x07, 0xff, 0x01, 0xe9, 0x1d, 0xc4, 0xfa, 0x67, 0xce, 0xab, 0x25, 0xc5, 0xf9, 0x7f, 0xd4,
	0xca, 0x40, 0xad, 0x6f, 0xe0, 0x8c, 0xd3, 0xfe, 0x0f, 0x68, 0x9d, 0x0c, 0x5b, 0x1b, 0xe7, 0xf9,
	0x72, 0x14, 0xee, 0x9b, 0xa9, 0x37, 0xbf, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x62, 0xb1, 0x35,
	0x74, 0xac, 0x01, 0x00, 0x00,
}
