// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package v2ray_core_internet_domainsocket is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	DomainSocketSecurity
	DomainSocketSettings
*/
package v2ray_core_internet_domainsocket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Flag Array
type DomainSocketSecurityMode int32

const (
	DomainSocketSecurityMode_Danger DomainSocketSecurityMode = 0
	// Verfify is Dialer have a pid or ppid match pid file
	DomainSocketSecurityMode_VerifyPid DomainSocketSecurityMode = 1
	// Do not tolerance ppid match
	DomainSocketSecurityMode_DisqualifyPPIDMatch DomainSocketSecurityMode = 2
	// Enforce Uid Verify On euid
	DomainSocketSecurityMode_VerifyEUID DomainSocketSecurityMode = 4
	// Enforce Uid Verify On ruid
	DomainSocketSecurityMode_VerifyRUID DomainSocketSecurityMode = 8
	// Does not allow same user exception
	DomainSocketSecurityMode_DisqualifySameUser DomainSocketSecurityMode = 16
	// Does not allow root user exception
	DomainSocketSecurityMode_DisqualifyRootUser DomainSocketSecurityMode = 32
)

var DomainSocketSecurityMode_name = map[int32]string{
	0:  "Danger",
	1:  "VerifyPid",
	2:  "DisqualifyPPIDMatch",
	4:  "VerifyEUID",
	8:  "VerifyRUID",
	16: "DisqualifySameUser",
	32: "DisqualifyRootUser",
}
var DomainSocketSecurityMode_value = map[string]int32{
	"Danger":              0,
	"VerifyPid":           1,
	"DisqualifyPPIDMatch": 2,
	"VerifyEUID":          4,
	"VerifyRUID":          8,
	"DisqualifySameUser":  16,
	"DisqualifyRootUser":  32,
}

func (x DomainSocketSecurityMode) String() string {
	return proto.EnumName(DomainSocketSecurityMode_name, int32(x))
}
func (DomainSocketSecurityMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DomainSocketSecurity struct {
	// Flag Array Type, User can set an integer to define various configure
	Mode DomainSocketSecurityMode `protobuf:"varint,1,opt,name=Mode,enum=v2ray.core.internet.domainsocket.DomainSocketSecurityMode" json:"Mode,omitempty"`
	// Set pid files to be allowed
	AllowedPid []string `protobuf:"bytes,2,rep,name=AllowedPid" json:"AllowedPid,omitempty"`
	// Set uids to be allowed, either euid or ruid should match one of following
	// uids AllowedUid, or user that v2ray is running or root.
	AllowedUid []uint64 `protobuf:"varint,3,rep,packed,name=AllowedUid" json:"AllowedUid,omitempty"`
}

func (m *DomainSocketSecurity) Reset()                    { *m = DomainSocketSecurity{} }
func (m *DomainSocketSecurity) String() string            { return proto.CompactTextString(m) }
func (*DomainSocketSecurity) ProtoMessage()               {}
func (*DomainSocketSecurity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DomainSocketSecurity) GetMode() DomainSocketSecurityMode {
	if m != nil {
		return m.Mode
	}
	return DomainSocketSecurityMode_Danger
}

func (m *DomainSocketSecurity) GetAllowedPid() []string {
	if m != nil {
		return m.AllowedPid
	}
	return nil
}

func (m *DomainSocketSecurity) GetAllowedUid() []uint64 {
	if m != nil {
		return m.AllowedUid
	}
	return nil
}

type DomainSocketSettings struct {
	// Path we should listen/dial
	Path     string                `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
	Security *DomainSocketSecurity `protobuf:"bytes,2,opt,name=Security" json:"Security,omitempty"`
}

func (m *DomainSocketSettings) Reset()                    { *m = DomainSocketSettings{} }
func (m *DomainSocketSettings) String() string            { return proto.CompactTextString(m) }
func (*DomainSocketSettings) ProtoMessage()               {}
func (*DomainSocketSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DomainSocketSettings) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DomainSocketSettings) GetSecurity() *DomainSocketSecurity {
	if m != nil {
		return m.Security
	}
	return nil
}

func init() {
	proto.RegisterType((*DomainSocketSecurity)(nil), "v2ray.core.internet.domainsocket.DomainSocketSecurity")
	proto.RegisterType((*DomainSocketSettings)(nil), "v2ray.core.internet.domainsocket.DomainSocketSettings")
	proto.RegisterEnum("v2ray.core.internet.domainsocket.DomainSocketSecurityMode", DomainSocketSecurityMode_name, DomainSocketSecurityMode_value)
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0x80, 0x4d, 0x7b, 0x94, 0xf6, 0xa9, 0x25, 0x3c, 0x45, 0x6f, 0x92, 0xd0, 0xe9, 0x70, 0xc8,
	0x50, 0xc1, 0xc1, 0x4d, 0x38, 0x87, 0x0e, 0x95, 0x23, 0xa5, 0xee, 0xf1, 0x92, 0xb6, 0xc1, 0x36,
	0xd1, 0x5c, 0xaa, 0x74, 0xf1, 0xa7, 0x38, 0xfa, 0x3b, 0xe5, 0x22, 0xda, 0x53, 0x14, 0xc1, 0x2d,
	0xef, 0x4b, 0xf2, 0xf1, 0x85, 0xc0, 0x5e, 0xe9, 0xec, 0xcc, 0xcc, 0xf9, 0xbd, 0x77, 0xc1, 0x21,
	0x7b, 0x1c, 0x7a, 0xb9, 0xe1, 0xa5, 0xf3, 0x9a, 0x1b, 0x1b, 0xb4, 0xb7, 0x3a, 0x70, 0xe5, 0x56,
	0xd2, 0xd8, 0xca, 0x95, 0x77, 0x3a, 0x0c, 0x5e, 0x09, 0x1c, 0xe6, 0x11, 0x4c, 0x22, 0x98, 0xe8,
	0x72, 0xed, 0x4d, 0xd8, 0xe0, 0x35, 0x24, 0x63, 0xa7, 0x74, 0x4a, 0x18, 0xc9, 0xfa, 0xc3, 0x0b,
	0xfe, 0x97, 0x89, 0xff, 0x64, 0xa9, 0x0d, 0x22, 0x7a, 0xf0, 0x04, 0xe0, 0x72, 0xb9, 0x74, 0x4f,
	0x5a, 0x15, 0x46, 0xa5, 0x2d, 0xd6, 0xce, 0x7a, 0xa2, 0x41, 0x1a, 0xfb, 0x53, 0xa3, 0xd2, 0x36,
	0x6b, 0x67, 0x89, 0x68, 0x90, 0xc1, 0xf3, 0xf7, 0xce, 0x10, 0x8c, 0x9d, 0x57, 0x88, 0x90, 0x14,
	0x32, 0x2c, 0x62, 0x67, 0x4f, 0xc4, 0x35, 0x0a, 0xe8, 0x7e, 0x14, 0xa4, 0x2d, 0x46, 0xb2, 0xdd,
	0xe1, 0xf9, 0xff, 0xfa, 0xc5, 0xa7, 0xe7, 0xf4, 0x85, 0x40, 0xfa, 0xdb, 0x13, 0x11, 0xa0, 0x93,
	0x4b, 0x3b, 0xd7, 0x9e, 0xee, 0xe0, 0x3e, 0xf4, 0x6e, 0xb4, 0x37, 0xb3, 0x4d, 0x61, 0x14, 0x25,
	0x78, 0x0c, 0x07, 0xb9, 0xa9, 0x1e, 0xd6, 0x72, 0x59, 0xa3, 0x62, 0x94, 0x8f, 0x65, 0x28, 0x17,
	0xb4, 0x85, 0x7d, 0x80, 0xf7, 0x73, 0x57, 0xd3, 0x51, 0x4e, 0x93, 0xed, 0x2c, 0xea, 0xb9, 0x8b,
	0x47, 0x80, 0xdb, 0x8b, 0x13, 0xb9, 0xd2, 0xd3, 0x4a, 0x7b, 0x4a, 0xbf, 0x72, 0xe1, 0x5c, 0x88,
	0x9c, 0xdd, 0x76, 0xe2, 0x97, 0x9f, 0xbd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xe1, 0xca, 0x78,
	0x02, 0x02, 0x00, 0x00,
}
