// Code generated by protoc-gen-go.
// source: v2ray.com/core/transport/internet/kcp/config.proto
// DO NOT EDIT!

/*
Package kcp is a generated protocol buffer package.

It is generated from these files:
	v2ray.com/core/transport/internet/kcp/config.proto

It has these top-level messages:
	MTU
	TTI
	UplinkCapacity
	DownlinkCapacity
	WriteBuffer
	ReadBuffer
	Config
*/
package kcp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import com_v2ray_core_transport_internet "v2ray.com/core/transport/internet"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Maximum Transmission Unit, in bytes.
type MTU struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *MTU) Reset()                    { *m = MTU{} }
func (m *MTU) String() string            { return proto.CompactTextString(m) }
func (*MTU) ProtoMessage()               {}
func (*MTU) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Transmission Time Interview, in milli-sec.
type TTI struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *TTI) Reset()                    { *m = TTI{} }
func (m *TTI) String() string            { return proto.CompactTextString(m) }
func (*TTI) ProtoMessage()               {}
func (*TTI) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Uplink capacity, in MB.
type UplinkCapacity struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *UplinkCapacity) Reset()                    { *m = UplinkCapacity{} }
func (m *UplinkCapacity) String() string            { return proto.CompactTextString(m) }
func (*UplinkCapacity) ProtoMessage()               {}
func (*UplinkCapacity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Downlink capacity, in MB.
type DownlinkCapacity struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *DownlinkCapacity) Reset()                    { *m = DownlinkCapacity{} }
func (m *DownlinkCapacity) String() string            { return proto.CompactTextString(m) }
func (*DownlinkCapacity) ProtoMessage()               {}
func (*DownlinkCapacity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type WriteBuffer struct {
	// Buffer size in bytes.
	Size uint32 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
}

func (m *WriteBuffer) Reset()                    { *m = WriteBuffer{} }
func (m *WriteBuffer) String() string            { return proto.CompactTextString(m) }
func (*WriteBuffer) ProtoMessage()               {}
func (*WriteBuffer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReadBuffer struct {
	// Buffer size in bytes.
	Size uint32 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
}

func (m *ReadBuffer) Reset()                    { *m = ReadBuffer{} }
func (m *ReadBuffer) String() string            { return proto.CompactTextString(m) }
func (*ReadBuffer) ProtoMessage()               {}
func (*ReadBuffer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Config struct {
	Mtu              *MTU                                                   `protobuf:"bytes,1,opt,name=mtu" json:"mtu,omitempty"`
	Tti              *TTI                                                   `protobuf:"bytes,2,opt,name=tti" json:"tti,omitempty"`
	UplinkCapacity   *UplinkCapacity                                        `protobuf:"bytes,3,opt,name=uplink_capacity,json=uplinkCapacity" json:"uplink_capacity,omitempty"`
	DownlinkCapacity *DownlinkCapacity                                      `protobuf:"bytes,4,opt,name=downlink_capacity,json=downlinkCapacity" json:"downlink_capacity,omitempty"`
	Congestion       bool                                                   `protobuf:"varint,5,opt,name=congestion" json:"congestion,omitempty"`
	WriteBuffer      *WriteBuffer                                           `protobuf:"bytes,6,opt,name=write_buffer,json=writeBuffer" json:"write_buffer,omitempty"`
	ReadBuffer       *ReadBuffer                                            `protobuf:"bytes,7,opt,name=read_buffer,json=readBuffer" json:"read_buffer,omitempty"`
	HeaderConfig     *com_v2ray_core_transport_internet.AuthenticatorConfig `protobuf:"bytes,8,opt,name=header_config,json=headerConfig" json:"header_config,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Config) GetMtu() *MTU {
	if m != nil {
		return m.Mtu
	}
	return nil
}

func (m *Config) GetTti() *TTI {
	if m != nil {
		return m.Tti
	}
	return nil
}

func (m *Config) GetUplinkCapacity() *UplinkCapacity {
	if m != nil {
		return m.UplinkCapacity
	}
	return nil
}

func (m *Config) GetDownlinkCapacity() *DownlinkCapacity {
	if m != nil {
		return m.DownlinkCapacity
	}
	return nil
}

func (m *Config) GetWriteBuffer() *WriteBuffer {
	if m != nil {
		return m.WriteBuffer
	}
	return nil
}

func (m *Config) GetReadBuffer() *ReadBuffer {
	if m != nil {
		return m.ReadBuffer
	}
	return nil
}

func (m *Config) GetHeaderConfig() *com_v2ray_core_transport_internet.AuthenticatorConfig {
	if m != nil {
		return m.HeaderConfig
	}
	return nil
}

func init() {
	proto.RegisterType((*MTU)(nil), "com.v2ray.core.transport.internet.kcp.MTU")
	proto.RegisterType((*TTI)(nil), "com.v2ray.core.transport.internet.kcp.TTI")
	proto.RegisterType((*UplinkCapacity)(nil), "com.v2ray.core.transport.internet.kcp.UplinkCapacity")
	proto.RegisterType((*DownlinkCapacity)(nil), "com.v2ray.core.transport.internet.kcp.DownlinkCapacity")
	proto.RegisterType((*WriteBuffer)(nil), "com.v2ray.core.transport.internet.kcp.WriteBuffer")
	proto.RegisterType((*ReadBuffer)(nil), "com.v2ray.core.transport.internet.kcp.ReadBuffer")
	proto.RegisterType((*Config)(nil), "com.v2ray.core.transport.internet.kcp.Config")
}

func init() { proto.RegisterFile("v2ray.com/core/transport/internet/kcp/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x93, 0xd1, 0xab, 0xda, 0x30,
	0x14, 0xc6, 0x71, 0x55, 0x27, 0xa7, 0xea, 0x5c, 0xd9, 0x43, 0xd9, 0x60, 0x38, 0x61, 0x43, 0xf6,
	0x90, 0xb2, 0x0e, 0xb7, 0x97, 0xbd, 0x4c, 0xf7, 0xe2, 0x83, 0x2f, 0xa1, 0x65, 0xb0, 0xc1, 0x24,
	0xa6, 0x51, 0x43, 0x35, 0x29, 0x31, 0x55, 0xdc, 0x9f, 0x7d, 0xff, 0x82, 0x4b, 0x53, 0x7b, 0xad,
	0x82, 0xf7, 0xf6, 0xbe, 0x19, 0x73, 0xbe, 0xdf, 0x49, 0xbf, 0xef, 0x1c, 0xf0, 0xf7, 0xbe, 0x22,
	0x47, 0x44, 0xe5, 0xd6, 0xa3, 0x52, 0x31, 0x4f, 0x2b, 0x22, 0x76, 0x89, 0x54, 0xda, 0xe3, 0x42,
	0x33, 0x25, 0x98, 0xf6, 0x62, 0x9a, 0x78, 0x54, 0x8a, 0x25, 0x5f, 0xa1, 0x44, 0x49, 0x2d, 0x9d,
	0x8f, 0x54, 0x6e, 0x51, 0xa1, 0x53, 0x0c, 0x3d, 0x68, 0x50, 0xa1, 0x41, 0x31, 0x4d, 0xde, 0x8e,
	0x9e, 0x46, 0x93, 0x54, 0xaf, 0x99, 0xd0, 0x9c, 0x12, 0x2d, 0x55, 0x4e, 0x1f, 0xbc, 0x03, 0x6b,
	0x16, 0x84, 0xce, 0x1b, 0x68, 0xec, 0xc9, 0x26, 0x65, 0x6e, 0xad, 0x5f, 0x1b, 0x76, 0x70, 0x7e,
	0xc8, 0x2e, 0x83, 0x60, 0x7a, 0xe3, 0xf2, 0x13, 0x74, 0xc3, 0x64, 0xc3, 0x45, 0x3c, 0x21, 0x09,
	0xa1, 0x5c, 0x1f, 0x6f, 0xd4, 0x0d, 0xa1, 0xf7, 0x4b, 0x1e, 0x44, 0x85, 0xca, 0x0f, 0x60, 0xff,
	0x56, 0x5c, 0xb3, 0x71, 0xba, 0x5c, 0x32, 0xe5, 0x38, 0x50, 0xdf, 0xf1, 0xff, 0x45, 0x8d, 0xf9,
	0x3d, 0xe8, 0x03, 0x60, 0x46, 0xa2, 0x47, 0x2a, 0xee, 0xea, 0xd0, 0x9c, 0x18, 0xff, 0x9c, 0x1f,
	0x60, 0x6d, 0x75, 0x6a, 0x6e, 0x6d, 0xff, 0x33, 0xaa, 0xe4, 0x23, 0x9a, 0x05, 0x21, 0xce, 0x64,
	0x99, 0x5a, 0x6b, 0xee, 0xbe, 0x78, 0x96, 0x3a, 0x08, 0xa6, 0x38, 0x93, 0x39, 0xff, 0xe0, 0x55,
	0x6a, 0xdc, 0x99, 0xd3, 0xd3, 0x47, 0xbb, 0x96, 0x21, 0x8d, 0x2a, 0x92, 0x2e, 0xbd, 0xc5, 0xdd,
	0xf4, 0xd2, 0xeb, 0x08, 0x5e, 0x47, 0x27, 0x57, 0xcf, 0x1d, 0xea, 0xa6, 0xc3, 0xf7, 0x8a, 0x1d,
	0xae, 0x53, 0xc1, 0xbd, 0xe8, 0x3a, 0xa7, 0xf7, 0x00, 0x54, 0x8a, 0x15, 0xdb, 0x69, 0x2e, 0x85,
	0xdb, 0xe8, 0xd7, 0x86, 0x2d, 0x5c, 0xfa, 0xc7, 0x09, 0xa1, 0x7d, 0xc8, 0x12, 0x9b, 0x2f, 0x4c,
	0x20, 0x6e, 0xd3, 0x3c, 0xc0, 0xaf, 0xf8, 0x80, 0x52, 0xd8, 0xd8, 0x3e, 0x94, 0x92, 0xc7, 0x60,
	0x2b, 0x46, 0xa2, 0x82, 0xfa, 0xd2, 0x50, 0xbf, 0x54, 0xa4, 0x9e, 0xe7, 0x03, 0x83, 0x3a, 0xcf,
	0xca, 0x5f, 0xe8, 0xac, 0x19, 0x89, 0x98, 0x9a, 0xe7, 0xdb, 0xe5, 0xb6, 0x0c, 0xf5, 0x5b, 0x05,
	0xea, 0xcf, 0xf2, 0xde, 0xe4, 0xb3, 0x85, 0xdb, 0x39, 0x2c, 0x3f, 0x8d, 0x1b, 0x7f, 0xac, 0x98,
	0x26, 0x8b, 0xa6, 0xd9, 0xa9, 0xaf, 0xf7, 0x01, 0x00, 0x00, 0xff, 0xff, 0x29, 0x6b, 0x1b, 0xbd,
	0xe7, 0x03, 0x00, 0x00,
}
