load("//bazel:build.bzl", "foreign_go_binary")
load("//bazel:gpg.bzl", "gpg_sign")
load("//bazel:matrix.bzl", "SUPPORTED_MATRIX")
load("//tools/control/main:targets.bzl", "gen_targets")

package(default_visibility=["//visibility:public"])

gen_targets(SUPPORTED_MATRIX)
