name: Dist
on:
  release:
    types: [published]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Download Files
      run: |
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-dragonfly-64.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-freebsd-32.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-freebsd-64.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-32.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-64.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-arm.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-arm64.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-mips.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-mips64.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-mips64le.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-s390x.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-macos.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-openbsd-32.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-openbsd-64.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-windows-32.zip &> /dev/null
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-windows-64.zip &> /dev/null
        wget https://github.com/v2ray/dist/raw/master/README.md &> /dev/null
        
    - name: Release
      run: |
        git init
        git add .
        git config user.name "Darien Raymond"
        git config user.email "admin@v2ray.com"
        
        TAG_URL="https://api.github.com/repos/v2ray/v2ray-core/releases/latest"
        NEW_VER=`curl -s ${TAG_URL} --connect-timeout 10| grep 'tag_name' | cut -d\" -f4`
        if [[ ${NEW_VER} != v* ]]; then
            NEW_VER=v${NEW_VER}
        fi
        
        git commit -m "Version ${NEW_VER}"
        git tag -a "${NEW_VER}" -m "Version ${NEW_VER}"
        git remote add origin "https://${{ secrets.DistAccessToken }}@github.com/v2ray/dist"
        git push -u --force --follow-tags origin master
